// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/notify/v1/notify.proto

package notifyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DestinationType int32

const (
	DestinationType_DESTINATION_TYPE_UNSPECIFIED DestinationType = 0
	DestinationType_DESTINATION_TYPE_WEBHOOK     DestinationType = 1
	DestinationType_DESTINATION_TYPE_EMAIL       DestinationType = 2
)

// Enum value maps for DestinationType.
var (
	DestinationType_name = map[int32]string{
		0: "DESTINATION_TYPE_UNSPECIFIED",
		1: "DESTINATION_TYPE_WEBHOOK",
		2: "DESTINATION_TYPE_EMAIL",
	}
	DestinationType_value = map[string]int32{
		"DESTINATION_TYPE_UNSPECIFIED": 0,
		"DESTINATION_TYPE_WEBHOOK":     1,
		"DESTINATION_TYPE_EMAIL":       2,
	}
)

func (x DestinationType) Enum() *DestinationType {
	p := new(DestinationType)
	*p = x
	return p
}

func (x DestinationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DestinationType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_notify_v1_notify_proto_enumTypes[0].Descriptor()
}

func (DestinationType) Type() protoreflect.EnumType {
	return &file_api_notify_v1_notify_proto_enumTypes[0]
}

func (x DestinationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DestinationType.Descriptor instead.
func (DestinationType) EnumDescriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{0}
}

type DeliveryStatus int32

const (
	DeliveryStatus_DELIVERY_STATUS_UNSPECIFIED DeliveryStatus = 0
	DeliveryStatus_DELIVERY_STATUS_PENDING     DeliveryStatus = 1
	DeliveryStatus_DELIVERY_STATUS_DELIVERING  DeliveryStatus = 2
	DeliveryStatus_DELIVERY_STATUS_DELIVERED   DeliveryStatus = 3
	DeliveryStatus_DELIVERY_STATUS_FAILED      DeliveryStatus = 4
	DeliveryStatus_DELIVERY_STATUS_RETRYING    DeliveryStatus = 5
)

// Enum value maps for DeliveryStatus.
var (
	DeliveryStatus_name = map[int32]string{
		0: "DELIVERY_STATUS_UNSPECIFIED",
		1: "DELIVERY_STATUS_PENDING",
		2: "DELIVERY_STATUS_DELIVERING",
		3: "DELIVERY_STATUS_DELIVERED",
		4: "DELIVERY_STATUS_FAILED",
		5: "DELIVERY_STATUS_RETRYING",
	}
	DeliveryStatus_value = map[string]int32{
		"DELIVERY_STATUS_UNSPECIFIED": 0,
		"DELIVERY_STATUS_PENDING":     1,
		"DELIVERY_STATUS_DELIVERING":  2,
		"DELIVERY_STATUS_DELIVERED":   3,
		"DELIVERY_STATUS_FAILED":      4,
		"DELIVERY_STATUS_RETRYING":    5,
	}
)

func (x DeliveryStatus) Enum() *DeliveryStatus {
	p := new(DeliveryStatus)
	*p = x
	return p
}

func (x DeliveryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_notify_v1_notify_proto_enumTypes[1].Descriptor()
}

func (DeliveryStatus) Type() protoreflect.EnumType {
	return &file_api_notify_v1_notify_proto_enumTypes[1]
}

func (x DeliveryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryStatus.Descriptor instead.
func (DeliveryStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{1}
}

type RegisterServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	WebhookUrl    string                 `protobuf:"bytes,2,opt,name=webhook_url,json=webhookUrl,proto3" json:"webhook_url,omitempty"`
	Secret        string                 `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServiceRequest) Reset() {
	*x = RegisterServiceRequest{}
	mi := &file_api_notify_v1_notify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServiceRequest) ProtoMessage() {}

func (x *RegisterServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServiceRequest.ProtoReflect.Descriptor instead.
func (*RegisterServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterServiceRequest) GetWebhookUrl() string {
	if x != nil {
		return x.WebhookUrl
	}
	return ""
}

func (x *RegisterServiceRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type RegisterServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServiceResponse) Reset() {
	*x = RegisterServiceResponse{}
	mi := &file_api_notify_v1_notify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServiceResponse) ProtoMessage() {}

func (x *RegisterServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServiceResponse.ProtoReflect.Descriptor instead.
func (*RegisterServiceResponse) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterServiceResponse) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *RegisterServiceResponse) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type ListServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesRequest) Reset() {
	*x = ListServicesRequest{}
	mi := &file_api_notify_v1_notify_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesRequest) ProtoMessage() {}

func (x *ListServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesRequest.ProtoReflect.Descriptor instead.
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{2}
}

type ListServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceInfo         `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesResponse) Reset() {
	*x = ListServicesResponse{}
	mi := &file_api_notify_v1_notify_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesResponse) ProtoMessage() {}

func (x *ListServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesResponse.ProtoReflect.Descriptor instead.
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{3}
}

func (x *ListServicesResponse) GetServices() []*ServiceInfo {
	if x != nil {
		return x.Services
	}
	return nil
}

type ServiceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	WebhookUrl    string                 `protobuf:"bytes,3,opt,name=webhook_url,json=webhookUrl,proto3" json:"webhook_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_api_notify_v1_notify_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceInfo) GetWebhookUrl() string {
	if x != nil {
		return x.WebhookUrl
	}
	return ""
}

type DeleteServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServiceRequest) Reset() {
	*x = DeleteServiceRequest{}
	mi := &file_api_notify_v1_notify_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceRequest) ProtoMessage() {}

func (x *DeleteServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceRequest.ProtoReflect.Descriptor instead.
func (*DeleteServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteServiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServiceResponse) Reset() {
	*x = DeleteServiceResponse{}
	mi := &file_api_notify_v1_notify_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceResponse) ProtoMessage() {}

func (x *DeleteServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceResponse.ProtoReflect.Descriptor instead.
func (*DeleteServiceResponse) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{6}
}

type SendNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Destinations  []*Destination         `protobuf:"bytes,4,rep,name=destinations,proto3" json:"destinations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationRequest) Reset() {
	*x = SendNotificationRequest{}
	mi := &file_api_notify_v1_notify_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationRequest) ProtoMessage() {}

func (x *SendNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendNotificationRequest) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{7}
}

func (x *SendNotificationRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *SendNotificationRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SendNotificationRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SendNotificationRequest) GetDestinations() []*Destination {
	if x != nil {
		return x.Destinations
	}
	return nil
}

type Destination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          DestinationType        `protobuf:"varint,1,opt,name=type,proto3,enum=notify.v1.DestinationType" json:"type,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Destination) Reset() {
	*x = Destination{}
	mi := &file_api_notify_v1_notify_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Destination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Destination) ProtoMessage() {}

func (x *Destination) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Destination.ProtoReflect.Descriptor instead.
func (*Destination) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{8}
}

func (x *Destination) GetType() DestinationType {
	if x != nil {
		return x.Type
	}
	return DestinationType_DESTINATION_TYPE_UNSPECIFIED
}

func (x *Destination) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type SendNotificationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendNotificationResponse) Reset() {
	*x = SendNotificationResponse{}
	mi := &file_api_notify_v1_notify_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationResponse) ProtoMessage() {}

func (x *SendNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationResponse.ProtoReflect.Descriptor instead.
func (*SendNotificationResponse) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{9}
}

func (x *SendNotificationResponse) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

type StreamDeliveryStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	ServiceId      string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamDeliveryStatusRequest) Reset() {
	*x = StreamDeliveryStatusRequest{}
	mi := &file_api_notify_v1_notify_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamDeliveryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDeliveryStatusRequest) ProtoMessage() {}

func (x *StreamDeliveryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDeliveryStatusRequest.ProtoReflect.Descriptor instead.
func (*StreamDeliveryStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{10}
}

func (x *StreamDeliveryStatusRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *StreamDeliveryStatusRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type DeliveryStatusEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	Destination    string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Status         DeliveryStatus         `protobuf:"varint,3,opt,name=status,proto3,enum=notify.v1.DeliveryStatus" json:"status,omitempty"`
	Message        string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Attempt        int32                  `protobuf:"varint,5,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeliveryStatusEvent) Reset() {
	*x = DeliveryStatusEvent{}
	mi := &file_api_notify_v1_notify_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryStatusEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryStatusEvent) ProtoMessage() {}

func (x *DeliveryStatusEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryStatusEvent.ProtoReflect.Descriptor instead.
func (*DeliveryStatusEvent) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{11}
}

func (x *DeliveryStatusEvent) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *DeliveryStatusEvent) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *DeliveryStatusEvent) GetStatus() DeliveryStatus {
	if x != nil {
		return x.Status
	}
	return DeliveryStatus_DELIVERY_STATUS_UNSPECIFIED
}

func (x *DeliveryStatusEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeliveryStatusEvent) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

type ListNotificationJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationJobsRequest) Reset() {
	*x = ListNotificationJobsRequest{}
	mi := &file_api_notify_v1_notify_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationJobsRequest) ProtoMessage() {}

func (x *ListNotificationJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationJobsRequest.ProtoReflect.Descriptor instead.
func (*ListNotificationJobsRequest) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{12}
}

func (x *ListNotificationJobsRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type ListNotificationJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*NotificationJob     `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationJobsResponse) Reset() {
	*x = ListNotificationJobsResponse{}
	mi := &file_api_notify_v1_notify_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationJobsResponse) ProtoMessage() {}

func (x *ListNotificationJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationJobsResponse.ProtoReflect.Descriptor instead.
func (*ListNotificationJobsResponse) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{13}
}

func (x *ListNotificationJobsResponse) GetJobs() []*NotificationJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type NotificationJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ServiceId     string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Event         string                 `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationJob) Reset() {
	*x = NotificationJob{}
	mi := &file_api_notify_v1_notify_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationJob) ProtoMessage() {}

func (x *NotificationJob) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationJob.ProtoReflect.Descriptor instead.
func (*NotificationJob) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{14}
}

func (x *NotificationJob) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *NotificationJob) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *NotificationJob) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *NotificationJob) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NotificationJob) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_api_notify_v1_notify_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{15}
}

func (x *GetStatsRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*StatEntry           `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_api_notify_v1_notify_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{16}
}

func (x *GetStatsResponse) GetStats() []*StatEntry {
	if x != nil {
		return x.Stats
	}
	return nil
}

type StatEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatEntry) Reset() {
	*x = StatEntry{}
	mi := &file_api_notify_v1_notify_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatEntry) ProtoMessage() {}

func (x *StatEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatEntry.ProtoReflect.Descriptor instead.
func (*StatEntry) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{17}
}

func (x *StatEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatEntry) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_api_notify_v1_notify_proto protoreflect.FileDescriptor

const file_api_notify_v1_notify_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/notify/v1/notify.proto\x12\tnotify.v1\"e\n" +
	"\x16RegisterServiceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vwebhook_url\x18\x02 \x01(\tR\n" +
	"webhookUrl\x12\x16\n" +
	"\x06secret\x18\x03 \x01(\tR\x06secret\"Q\n" +
	"\x17RegisterServiceResponse\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\"\x15\n" +
	"\x13ListServicesRequest\"J\n" +
	"\x14ListServicesResponse\x122\n" +
	"\bservices\x18\x01 \x03(\v2\x16.notify.v1.ServiceInfoR\bservices\"R\n" +
	"\vServiceInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vwebhook_url\x18\x03 \x01(\tR\n" +
	"webhookUrl\"&\n" +
	"\x14DeleteServiceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x17\n" +
	"\x15DeleteServiceResponse\"\xa4\x01\n" +
	"\x17SendNotificationRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12:\n" +
	"\fdestinations\x18\x04 \x03(\v2\x16.notify.v1.DestinationR\fdestinations\"U\n" +
	"\vDestination\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.notify.v1.DestinationTypeR\x04type\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\"C\n" +
	"\x18SendNotificationResponse\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\"e\n" +
	"\x1bStreamDeliveryStatusRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\"\xc7\x01\n" +
	"\x13DeliveryStatusEvent\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x121\n" +
	"\x06status\x18\x03 \x01(\x0e2\x19.notify.v1.DeliveryStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x18\n" +
	"\aattempt\x18\x05 \x01(\x05R\aattempt\"<\n" +
	"\x1bListNotificationJobsRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\"N\n" +
	"\x1cListNotificationJobsResponse\x12.\n" +
	"\x04jobs\x18\x01 \x03(\v2\x1a.notify.v1.NotificationJobR\x04jobs\"\x9c\x01\n" +
	"\x0fNotificationJob\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x12\x14\n" +
	"\x05event\x18\x03 \x01(\tR\x05event\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"0\n" +
	"\x0fGetStatsRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\">\n" +
	"\x10GetStatsResponse\x12*\n" +
	"\x05stats\x18\x01 \x03(\v2\x14.notify.v1.StatEntryR\x05stats\"9\n" +
	"\tStatEntry\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count*m\n" +
	"\x0fDestinationType\x12 \n" +
	"\x1cDESTINATION_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18DESTINATION_TYPE_WEBHOOK\x10\x01\x12\x1a\n" +
	"\x16DESTINATION_TYPE_EMAIL\x10\x02*\xc7\x01\n" +
	"\x0eDeliveryStatus\x12\x1f\n" +
	"\x1bDELIVERY_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17DELIVERY_STATUS_PENDING\x10\x01\x12\x1e\n" +
	"\x1aDELIVERY_STATUS_DELIVERING\x10\x02\x12\x1d\n" +
	"\x19DELIVERY_STATUS_DELIVERED\x10\x03\x12\x1a\n" +
	"\x16DELIVERY_STATUS_FAILED\x10\x04\x12\x1c\n" +
	"\x18DELIVERY_STATUS_RETRYING\x10\x052\xfb\x04\n" +
	"\rNotifyService\x12X\n" +
	"\x0fRegisterService\x12!.notify.v1.RegisterServiceRequest\x1a\".notify.v1.RegisterServiceResponse\x12O\n" +
	"\fListServices\x12\x1e.notify.v1.ListServicesRequest\x1a\x1f.notify.v1.ListServicesResponse\x12R\n" +
	"\rDeleteService\x12\x1f.notify.v1.DeleteServiceRequest\x1a .notify.v1.DeleteServiceResponse\x12[\n" +
	"\x10SendNotification\x12\".notify.v1.SendNotificationRequest\x1a#.notify.v1.SendNotificationResponse\x12`\n" +
	"\x14StreamDeliveryStatus\x12&.notify.v1.StreamDeliveryStatusRequest\x1a\x1e.notify.v1.DeliveryStatusEvent0\x01\x12g\n" +
	"\x14ListNotificationJobs\x12&.notify.v1.ListNotificationJobsRequest\x1a'.notify.v1.ListNotificationJobsResponse\x12C\n" +
	"\bGetStats\x12\x1a.notify.v1.GetStatsRequest\x1a\x1b.notify.v1.GetStatsResponseB:Z8github.com/lupppig/notifyctl/pkg/grpc/notify/v1;notifyv1b\x06proto3"

var (
	file_api_notify_v1_notify_proto_rawDescOnce sync.Once
	file_api_notify_v1_notify_proto_rawDescData []byte
)

func file_api_notify_v1_notify_proto_rawDescGZIP() []byte {
	file_api_notify_v1_notify_proto_rawDescOnce.Do(func() {
		file_api_notify_v1_notify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_notify_v1_notify_proto_rawDesc), len(file_api_notify_v1_notify_proto_rawDesc)))
	})
	return file_api_notify_v1_notify_proto_rawDescData
}

var file_api_notify_v1_notify_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_notify_v1_notify_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_notify_v1_notify_proto_goTypes = []any{
	(DestinationType)(0),                 // 0: notify.v1.DestinationType
	(DeliveryStatus)(0),                  // 1: notify.v1.DeliveryStatus
	(*RegisterServiceRequest)(nil),       // 2: notify.v1.RegisterServiceRequest
	(*RegisterServiceResponse)(nil),      // 3: notify.v1.RegisterServiceResponse
	(*ListServicesRequest)(nil),          // 4: notify.v1.ListServicesRequest
	(*ListServicesResponse)(nil),         // 5: notify.v1.ListServicesResponse
	(*ServiceInfo)(nil),                  // 6: notify.v1.ServiceInfo
	(*DeleteServiceRequest)(nil),         // 7: notify.v1.DeleteServiceRequest
	(*DeleteServiceResponse)(nil),        // 8: notify.v1.DeleteServiceResponse
	(*SendNotificationRequest)(nil),      // 9: notify.v1.SendNotificationRequest
	(*Destination)(nil),                  // 10: notify.v1.Destination
	(*SendNotificationResponse)(nil),     // 11: notify.v1.SendNotificationResponse
	(*StreamDeliveryStatusRequest)(nil),  // 12: notify.v1.StreamDeliveryStatusRequest
	(*DeliveryStatusEvent)(nil),          // 13: notify.v1.DeliveryStatusEvent
	(*ListNotificationJobsRequest)(nil),  // 14: notify.v1.ListNotificationJobsRequest
	(*ListNotificationJobsResponse)(nil), // 15: notify.v1.ListNotificationJobsResponse
	(*NotificationJob)(nil),              // 16: notify.v1.NotificationJob
	(*GetStatsRequest)(nil),              // 17: notify.v1.GetStatsRequest
	(*GetStatsResponse)(nil),             // 18: notify.v1.GetStatsResponse
	(*StatEntry)(nil),                    // 19: notify.v1.StatEntry
}
var file_api_notify_v1_notify_proto_depIdxs = []int32{
	6,  // 0: notify.v1.ListServicesResponse.services:type_name -> notify.v1.ServiceInfo
	10, // 1: notify.v1.SendNotificationRequest.destinations:type_name -> notify.v1.Destination
	0,  // 2: notify.v1.Destination.type:type_name -> notify.v1.DestinationType
	1,  // 3: notify.v1.DeliveryStatusEvent.status:type_name -> notify.v1.DeliveryStatus
	16, // 4: notify.v1.ListNotificationJobsResponse.jobs:type_name -> notify.v1.NotificationJob
	19, // 5: notify.v1.GetStatsResponse.stats:type_name -> notify.v1.StatEntry
	2,  // 6: notify.v1.NotifyService.RegisterService:input_type -> notify.v1.RegisterServiceRequest
	4,  // 7: notify.v1.NotifyService.ListServices:input_type -> notify.v1.ListServicesRequest
	7,  // 8: notify.v1.NotifyService.DeleteService:input_type -> notify.v1.DeleteServiceRequest
	9,  // 9: notify.v1.NotifyService.SendNotification:input_type -> notify.v1.SendNotificationRequest
	12, // 10: notify.v1.NotifyService.StreamDeliveryStatus:input_type -> notify.v1.StreamDeliveryStatusRequest
	14, // 11: notify.v1.NotifyService.ListNotificationJobs:input_type -> notify.v1.ListNotificationJobsRequest
	17, // 12: notify.v1.NotifyService.GetStats:input_type -> notify.v1.GetStatsRequest
	3,  // 13: notify.v1.NotifyService.RegisterService:output_type -> notify.v1.RegisterServiceResponse
	5,  // 14: notify.v1.NotifyService.ListServices:output_type -> notify.v1.ListServicesResponse
	8,  // 15: notify.v1.NotifyService.DeleteService:output_type -> notify.v1.DeleteServiceResponse
	11, // 16: notify.v1.NotifyService.SendNotification:output_type -> notify.v1.SendNotificationResponse
	13, // 17: notify.v1.NotifyService.StreamDeliveryStatus:output_type -> notify.v1.DeliveryStatusEvent
	15, // 18: notify.v1.NotifyService.ListNotificationJobs:output_type -> notify.v1.ListNotificationJobsResponse
	18, // 19: notify.v1.NotifyService.GetStats:output_type -> notify.v1.GetStatsResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_notify_v1_notify_proto_init() }
func file_api_notify_v1_notify_proto_init() {
	if File_api_notify_v1_notify_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_notify_v1_notify_proto_rawDesc), len(file_api_notify_v1_notify_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_notify_v1_notify_proto_goTypes,
		DependencyIndexes: file_api_notify_v1_notify_proto_depIdxs,
		EnumInfos:         file_api_notify_v1_notify_proto_enumTypes,
		MessageInfos:      file_api_notify_v1_notify_proto_msgTypes,
	}.Build()
	File_api_notify_v1_notify_proto = out.File
	file_api_notify_v1_notify_proto_goTypes = nil
	file_api_notify_v1_notify_proto_depIdxs = nil
}
